# .github/workflows/health-check.yml

name: health-check


on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  health-check:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
      # run cron job
      - name: echo
        run: echo "test"
